/*
CREATED BY: EDWARD DANNEMILLER
CREATED ON: 05/24/2022
DESCRIPTION: tHIS QUERY SELECTS THE FIRST NAME, LAST NAME, AND EMAIL ADDRESS FROM THE CUSTOMERS TABLE 
*/
SELECT
	FirstName, LastName, Email
FROM
	customers